let allSentences = [{
    name: "Sentence One",
    key: [
        ["I", "feel", "great"],
        ["she", "was", "late"],
        ["is", "dinner", "ready"],
        ["he", "will", "call"],
        ["light", "the", "fire"],
        ["eat", "your", "lunch"],
        ["it", "is", "late"],
        ["drink", "your", "milk"],
        ["how", "are", "you"],
        ["wash", "your", "hair"],
        ["that's", "very", "nice"],
        ["I", "am", "hungry"],
        ["who", "are", "you"],
        ["sit", "over", "there"],
        ["the", "dog", "ran"],
        ["we", "ate", "lunch"],
        ["tie", "your", "shoe"],
        ["we", "went", "downtown"],
        ["open", "the", "door"],
        ["ride", "the", "bike"],
        ["do", "not", "hurry"],
        ["pass", "the", "salt"],
        ["we", "left", "early"],
        ["open", "the", "window"],
        ["pitch", "the", "tent"],
    ],
}, { 
    name: "Sentence Two",
    key: [
        ["the", "lion", "roared"],
        ["brush", "your", "hair"],
        ["it's", "snowing", "outside"],
        ["don't", "look", "back"],
        ["he", "played", "baseball"],
        ["rang", "the", "alarm"],
        ["what", "is", "dripping"],
        ["he", "delivers", "mail"],
        ["wear", "your", "coat"],
        ["have", "times", "changed"],
        ["time", "for", "lunch"],
        ["where", "were", "you"],
        ["thanks", "for", "coming"],
        ["cross", "the", "bridge"],
        ["turn", "it", "down"],
        ["John", "left", "town"],
        ["rang", "the", "phone"],
        ["close", "the", "gate"],
        ["watch", "the", "movie"],
        ["please", "wait", "outside"],
        ["water", "the", "plant"],
        ["butter", "the", "toast"],
        ["drive", "the", "car"],
        ["the", "woman", "tripped"],
        ["climb", "the", "tree"],   
    ],
}, {
    name: "Sentence Three",
    key: [
        ["I wish I was"],
        ["I ate everything on my"],
        ["I'm in no particular"],
        ["Must you go"],
        ["At 5:30 we eat"],
        ["His goal in life was to write a"],
        ["On Saturday he bought a new"],
        ["The movie started at"],
        ["They took a walk around the"],
        ["She wore the ring on her"],
        ["He took a picture with his"],
        ["He lit the fire with a"],
        ["The car was out of"],
        ["It is illegal to"],
        ["For her birthday, he bought a"],
        ["They were followed by two"],
        ["Tyler and Joe went swimming at the"],
        ["Please turn on the"],
        ["Maria went running every"],
        ["He mows the lawn on"],
        ["It has been snowing for three"],
        ["He put salt and pepper on his"],
        ["The boy took his dog for a"],
        ["They went to London for their"],
        ["I like butter on my"],
    ],
}, { 
    name: "Sentence Four",
    key: [ 
        ["She went"],
        ["They bought a"],
        ["I ate"],
        ["For three years, I have been"],
        ["The boat sailed"],
        ["He sang"],
        ["Yesterday I saw"],
        ["We barbecued"],
        ["Golfing is"],
        ["The children were"],
        ["In the summer, they go"],
        ["Tom and Jessica were"],
        ["The old man and his wife"],
        ["They found"],
        ["He watched"],
        ["Sometimes I like"],
        ["It was"],
        ["We've been"],
        ["The dog ran"],
        ["What are"],
        ["Fourteen geese were"],
        ["The music was"],
        ["It took"],
        ["Hunting is"],
        ["Maybe we should"],
    ],
}];
