/*
Eragon, Saphira, and Roran travel to Helgrind, the home of the Ra'zac. There, they rescue Roran's betrothed, Katrina, held prisoner there, and kill one of the Ra'zac. Saphira, Roran, and Katrina return to the Varden, while Eragon stays behind. Eragon slays the remaining Ra'zac, who warns him that Galbatorix has discovered "the name". Eragon also finds and condemns Sloan, Katrina's treacherous father, to never meet his daughter again, and arranges for him to travel to Ellesmera, the elven homeland.

Eragon then travels back to the Varden, after reuniting with Arya, who had come in search of him. Once they return to the Varden, Eragon discovers that Katrina is pregnant with Roran's child and a wedding is arranged, which Eragon is to conduct. Just before it begins, a small force of troops attack alongside Murtagh and his dragon, Thorn. The soldiers had spells cast on them that removed their ability to feel pain, making them better fighters. Elven spell-casters aid Eragon and Saphira and cause Murtagh and Thorn to flee, winning the battle. After the fight, Roran marries Katrina.

The leader of the Varden, Nasuada, orders Eragon to attend the election of the new dwarf king in the Beor Mountains, while Saphira stays behind to protect the Varden. Eragon is to support the bid of Orik, the former king's adoptive son, who favors the Varden. Eragon heads to Farthen Dur, where the election takes place. Once there, Eragon is the target of an assassination attempt, perpetrated by a Rider-hating dwarf clan, whom Orik forces into exile. Having earned the sympathies of the dwarves, Orik is elected the new king. Saphira journeys to Farthen Dur for Orik's coronation and repairs Isidar Mithrim, the previously destroyed star rose.

After Orik's coronation, Eragon and Saphira journey to Ellesméra to learn the secret of Galbatorix's power. There, they learn that Eragon's deceased mentor, Brom, was Eragon's father. Glaedr also reveals the source of Galbatorix's power: Eldunari, a dragon organ, which allows its holder to communicate with and draw energy from the dragon it belongs to, even if the dragon is deceased. Galbatorix spent years collecting Eldunari, drawing his power from the dragons he slew.

After some training, Eragon visits Rhunön, the elven blacksmith who forged swords for Riders. Rhunön refuses to forge Eragon a new sword, having sworn to never create a weapon again, and having depleted her stocks of the required metal. By deciphering the werecat Solembum's instructions, Eragon acquires the metal from under the roots of the Menoa Tree. Rhunön forges him a sword by controlling Eragon's body, and he names it "Brisingr", which causes it to burst into flames whenever its name is said aloud.

Oromis and Glaedr decide to join the battle against the Empire alongside Islanzadí. To prevent Galbatorix from claiming his Eldunari should he fall in combat, and to continue guiding Eragon, Glaedr gives his Eldunari to Eragon. Glaedr and Oromis fly to Gil'ead, while Eragon and Saphira fly to Feinster, a city sieged by the Varden.

Meanwhile, Roran is sent on various missions as a soldier of the Varden. One mission against soldiers that can't feel pain results in many casualties, and in Roran being assigned to an incompetent commander. During another mission, this commander almost causes the entire force to be decimated. Roran takes charge of a small group of soldiers loyal to him, and leads them to victory against overwhelming odds. Despite this, Roran is charged with insubordination and is flogged as a punishment. Afterwards, Nasuada promotes Roran to commander and sends his unit on a mission with both men and Urgals, to enforce the idea of men and Urgals working together. When an Urgal, Yarbog, challenges Roran for leadership of the unit, he wrestles him into submission. After returning to the Varden, his squad joins the siege of Feinster.

As the siege begins, Eragon rescues Arya and departs to find the leader of the city, but discovers three magicians attempting to create a Shade. While attempting to kill the magicians, Eragon has a vision through Glaedr's Eldunarí showing him and Oromis fighting Murtagh and Thorn in the sky. During the fight, Galbatorix takes control of Murtagh, and tries to lure Oromis to his side. Failing to do so, he slays Oromis as he suffers a seizure. Glaedr, in grief, is also killed. After the vision, the magicians succeed in creating the Shade Varaug. Eragon and Arya fight and slay Varaug, with Arya dealing the fatal blow. After the successful siege, Eragon resolves to continue the fight against the Empire, to avenge Oromis and Glaedr.
*/
['c','d'];
