'use strict';

let consonant = [{ 
    letter: "p",
    mp3: "files/consonant-p.mp3",
}, { 
    letter: "b", 
    mp3: "files/consonant-b.mp3",
}, { 
    letter: "f", 
    mp3: "files/consonant-f.mp3",
}, { 
    letter: "v", 
    mp3: "files/consonant-v.mp3",
}, { 
    letter: "t", 
    mp3: "files/consonant-t.mp3",
}, { 
    letter: "d", 
    mp3: "files/consonant-d.mp3",
}, { 
    letter: "c/k", 
    mp3: "files/consonant-k.mp3",
}, { 
    letter: "g", 
    mp3: "files/consonant-g.mp3",
}, { 
    letter: "th", 
    mp3: "files/consonant-th-quiet.mp3",
}, { 
    letter: "TH", 
    mp3: "files/consonant-th-noisy.mp3",
}, { 
    letter: "s", 
    mp3: "files/consonant-s.mp3",
}, { 
    letter: "z", 
    mp3: "files/consonant-z.mp3",
}, { 
    letter: "sh", 
    mp3: "files/consonant-sh.mp3",
}, { 
    letter: "su/zh/zu", 
    mp3: "files/consonant-zh.mp3",
}, { 
    letter: "ch", 
    mp3: "files/consonant-ch.mp3",
}, { 
    letter: "j", 
    mp3: "files/consonant-j.mp3",
}, { 
    letter: "m", 
    mp3: "files/consonant-m.mp3",
}, { 
    letter: "n", 
    mp3: "files/consonant-n.mp3",
}, { 
    letter: "ng", 
    mp3: "files/consonant-ng.mp3",
}, { 
    letter: "l", 
    mp3: "files/consonant-l.mp3",
}, { 
    letter: "r", 
    mp3: "files/consonant-r.mp3",
}, { 
    letter: "h", 
    mp3: "files/consonant-h.mp3",
}, { 
    letter: "w", 
    mp3: "files/consonant-w.mp3",
}];

let vowel = [{ 
    letter: "ee", 
    mp3: "files/vowel-ee.mp3",
}, { 
    letter: "i", 
    mp3: "files/vowel-i.mp3",
}, { 
    letter: "e", 
    mp3: "files/vowel-e.mp3",
}, { 
    letter: "ae", 
    mp3: "files/vowel-ae.mp3",
}, { 
    letter: "a", 
    mp3: "files/vowel-a.mp3",
}, { 
    letter: "u", 
    mp3: "files/vowel-u.mp3",
}, { 
    letter: "au/aw/o", 
    mp3: "files/vowel-au-aw-o.mp3",
}, { 
    letter: "oe", 
    mp3: "files/vowel-oe.mp3",
}, { 
    letter: "uu", 
    mp3: "files/vowel-uu.mp3",
}, { 
    letter: "oo", 
    mp3: "files/vowel-oo.mp3",
}, { 
    letter: "ie", 
    mp3: "files/vowel-ie.mp3",
}, { 
    letter: "ue", 
    mp3: "files/vowel-ue.mp3",
}, { 
    letter: "ou/ow", 
    mp3: "files/vowel-ou-ow.mp3",
}, { 
    letter: "oi/oy", 
    mp3: "files/vowel-oi-oy.mp3",
}, { 
    letter: "er/ir/ur", 
    mp3: "files/vowel-er-ir-ur.mp3",
}, { 
    letter: "ar", 
    mp3: "files/vowel-ar.mp3",
}, { 
    letter: "or", 
    mp3: "files/vowel-or.mp3",
}];
