'use strict';

function fn_hiragana() {

	const hiragana = [{
		'english': 'a',
		'gif': 'hiragana-あ.gif',
		'png': 'hiragana-あ.png',
		'japanese': 'あ',
	}, {
		'english': 'i',
		'gif': 'hiragana-い.gif',
		'png': 'hiragana-い.png',
		'japanese': 'い',
	}, {
		'english': 'u',
		'gif': 'hiragana-う.gif',
		'png': 'hiragana-う.png',
		'japanese': 'う',
	}, {
		'english': 'e',
		'gif': 'hiragana-え.gif',
		'png': 'hiragana-え.png',
		'japanese': 'え',
	}, {
		'english': 'o',
		'gif': 'hiragana-お.gif',
		'png': 'hiragana-お.png',
		'japanese': 'お',
	}, {
		'english': 'ka',
		'gif': 'hiragana-か.gif',
		'png': 'hiragana-か.png',
		'japanese': 'か',
	}, {
		'english': 'ki',
		'gif': 'hiragana-き.gif',
		'png': 'hiragana-き.png',
		'japanese': 'き',
	}, {
		'english': 'ku',
		'gif': 'hiragana-く.gif',
		'png': 'hiragana-く.png',
		'japanese': 'く',
	}, {
		'english': 'ke',
		'gif': 'hiragana-け.gif',
		'png': 'hiragana-け.png',
		'japanese': 'け',
	}, {
		'english': 'ko',
		'gif': 'hiragana-こ.gif',
		'png': 'hiragana-こ.png',
		'japanese': 'こ',
	}, {
		'english': 'sa',
		'gif': 'hiragana-さ.gif',
		'png': 'hiragana-さ.png',
		'japanese': 'さ',
	}, {
		'english': 'shi',
		'gif': 'hiragana-し.gif',
		'png': 'hiragana-し.png',
		'japanese': 'し',
	}, {
		'english': 'su',
		'gif': 'hiragana-す.gif',
		'png': 'hiragana-す.png',
		'japanese': 'す',
	}, {
		'english': 'se',
		'gif': 'hiragana-せ.gif',
		'png': 'hiragana-せ.png',
		'japanese': 'せ',
	}, {
		'english': 'so',
		'gif': 'hiragana-そ.gif',
		'png': 'hiragana-そ.png',
		'japanese': 'そ',
	}, {
		'english': 'ta',
		'gif': 'hiragana-た.gif',
		'png': 'hiragana-た.png',
		'japanese': 'た',
	}, {
		'english': 'chi',
		'gif': 'hiragana-ち.gif',
		'png': 'hiragana-ち.png',
		'japanese': 'ち',
	}, {
		'english': 'tsu',
		'gif': 'hiragana-つ.gif',
		'png': 'hiragana-つ.png',
		'japanese': 'つ',
	}, {
		'english': 'te',
		'gif': 'hiragana-て.gif',
		'png': 'hiragana-て.png',
		'japanese': 'て',
	}, {
		'english': 'to',
		'gif': 'hiragana-と.gif',
		'png': 'hiragana-と.png',
		'japanese': 'と',
	}, {
		'english': 'na',
		'gif': 'hiragana-な.gif',
		'png': 'hiragana-な.png',
		'japanese': 'な',
	}, {
		'english': 'ni',
		'gif': 'hiragana-に.gif',
		'png': 'hiragana-に.png',
		'japanese': 'に',
	}, {
		'english': 'nu',
		'gif': 'hiragana-ぬ.gif',
		'png': 'hiragana-ぬ.png',
		'japanese': 'ぬ',
	}, {
		'english': 'ne',
		'gif': 'hiragana-ね.gif',
		'png': 'hiragana-ね.png',
		'japanese': 'ね',
	}, {
		'english': 'no',
		'gif': 'hiragana-の.gif',
		'png': 'hiragana-の.png',
		'japanese': 'の',
	}, {
		'english': 'ha',
		'gif': 'hiragana-は.gif',
		'png': 'hiragana-は.png',
		'japanese': 'は',
	}, {
		'english': 'hi',
		'gif': 'hiragana-ひ.gif',
		'png': 'hiragana-ひ.png',
		'japanese': 'ひ',
	}, {
		'english': 'fu',
		'gif': 'hiragana-ふ.gif',
		'png': 'hiragana-ふ.png',
		'japanese': 'ふ',
	}, {
		'english': 'he',
		'gif': 'hiragana-へ.gif',
		'png': 'hiragana-へ.png',
		'japanese': 'へ',
	}, {
		'english': 'ho',
		'gif': 'hiragana-ほ.gif',
		'png': 'hiragana-ほ.png',
		'japanese': 'ほ',
	}, {
		'english': 'ma',
		'gif': 'hiragana-ま.gif',
		'png': 'hiragana-ま.png',
		'japanese': 'ま',
	}, {
		'english': 'mi',
		'gif': 'hiragana-み.gif',
		'png': 'hiragana-み.png',
		'japanese': 'み',
	}, {
		'english': 'mu',
		'gif': 'hiragana-む.gif',
		'png': 'hiragana-む.png',
		'japanese': 'む',
	}, {
		'english': 'me',
		'gif': 'hiragana-め.gif',
		'png': 'hiragana-め.png',
		'japanese': 'め',
	}, {
		'english': 'mo',
		'gif': 'hiragana-も.gif',
		'png': 'hiragana-も.png',
		'japanese': 'も',
	}, {
		'english': 'ya',
		'gif': 'hiragana-や.gif',
		'png': 'hiragana-や.png',
		'japanese': 'や',
	}, {
		'english': 'yu',
		'gif': 'hiragana-ゆ.gif',
		'png': 'hiragana-ゆ.png',
		'japanese': 'ゆ',
	}, {
		'english': 'yo',
		'gif': 'hiragana-よ.gif',
		'png': 'hiragana-よ.png',
		'japanese': 'よ',
	}, {
		'english': 'ra',
		'gif': 'hiragana-ら.gif',
		'png': 'hiragana-ら.png',
		'japanese': 'ら',
	}, {
		'english': 'ri',
		'gif': 'hiragana-り.gif',
		'png': 'hiragana-り.png',
		'japanese': 'り',
	}, {
		'english': 'ru',
		'gif': 'hiragana-る.gif',
		'png': 'hiragana-る.png',
		'japanese': 'る',
	}, {
		'english': 're',
		'gif': 'hiragana-れ.gif',
		'png': 'hiragana-れ.png',
		'japanese': 'れ',
	}, {
		'english': 'ro',
		'gif': 'hiragana-ろ.gif',
		'png': 'hiragana-ろ.png',
		'japanese': 'ろ',
	}, {
		'english': 'wa',
		'gif': 'hiragana-わ.gif',
		'png': 'hiragana-わ.png',
		'japanese': 'わ',
	}, {
		'english': 'wo',
		'gif': 'hiragana-を.gif',
		'png': 'hiragana-を.png',
		'japanese': 'を',
	}, {
		'english': 'n',
		'gif': 'hiragana-ん.gif',
		'png': 'hiragana-ん.png',
		'japanese': 'ん',
	}];

	return hiragana;
}

function fn_katakana() {

	const katakana = [{
		'english': 'a',
		'gif': 'katakana-ア.gif',
		'png': 'katakana-ア.png',
		'japanese': 'ア',
	}, {
		'english': 'i',
		'gif': 'katakana-イ.gif',
		'png': 'katakana-イ.png',
		'japanese': 'イ',
	}, {
		'english': 'u',
		'gif': 'katakana-ウ.gif',
		'png': 'katakana-ウ.png',
		'japanese': 'ウ',
	}, {
		'english': 'e',
		'gif': 'katakana-エ.gif',
		'png': 'katakana-エ.png',
		'japanese': 'エ',
	}, {
		'english': 'o',
		'gif': 'katakana-オ.gif',
		'png': 'katakana-オ.png',
		'japanese': 'オ',
	}, {
		'english': 'ka',
		'gif': 'katakana-カ.gif',
		'png': 'katakana-カ.png',
		'japanese': 'カ',
	}, {
		'english': 'ki',
		'gif': 'katakana-キ.gif',
		'png': 'katakana-キ.png',
		'japanese': 'キ',
	}, {
		'english': 'ku',
		'gif': 'katakana-ク.gif',
		'png': 'katakana-ク.png',
		'japanese': 'ク',
	}, {
		'english': 'ke',
		'gif': 'katakana-ケ.gif',
		'png': 'katakana-ケ.png',
		'japanese': 'ケ',
	}, {
		'english': 'ko',
		'gif': 'katakana-コ.gif',
		'png': 'katakana-コ.png',
		'japanese': 'コ',
	}, {
		'english': 'sa',
		'gif': 'katakana-サ.gif',
		'png': 'katakana-サ.png',
		'japanese': 'サ',
	}, {
		'english': 'shi',
		'gif': 'katakana-シ.gif',
		'png': 'katakana-シ.png',
		'japanese': 'シ',
	}, {
		'english': 'su',
		'gif': 'katakana-ス.gif',
		'png': 'katakana-ス.png',
		'japanese': 'ス',
	}, {
		'english': 'se',
		'gif': 'katakana-セ.gif',
		'png': 'katakana-セ.png',
		'japanese': 'セ',
	}, {
		'english': 'so',
		'gif': 'katakana-ソ.gif',
		'png': 'katakana-ソ.png',
		'japanese': 'ソ',
	}, {
		'english': 'ta',
		'gif': 'katakana-タ.gif',
		'png': 'katakana-タ.png',
		'japanese': 'タ',
	}, {
		'english': 'chi',
		'gif': 'katakana-チ.gif',
		'png': 'katakana-チ.png',
		'japanese': 'チ',
	}, {
		'english': 'tsu',
		'gif': 'katakana-ツ.gif',
		'png': 'katakana-ツ.png',
		'japanese': 'ツ',
	}, {
		'english': 'te',
		'gif': 'katakana-テ.gif',
		'png': 'katakana-テ.png',
		'japanese': 'テ',
	}, {
		'english': 'to',
		'gif': 'katakana-ト.gif',
		'png': 'katakana-ト.png',
		'japanese': 'ト',
	}, {
		'english': 'na',
		'gif': 'katakana-ナ.gif',
		'png': 'katakana-ナ.png',
		'japanese': 'ナ',
	}, {
		'english': 'ni',
		'gif': 'katakana-ニ.gif',
		'png': 'katakana-ニ.png',
		'japanese': 'ニ',
	}, {
		'english': 'nu',
		'gif': 'katakana-ヌ.gif',
		'png': 'katakana-ヌ.png',
		'japanese': 'ヌ',
	}, {
		'english': 'ne',
		'gif': 'katakana-ネ.gif',
		'png': 'katakana-ネ.png',
		'japanese': 'ネ',
	}, {
		'english': 'no',
		'gif': 'katakana-ノ.gif',
		'png': 'katakana-ノ.png',
		'japanese': 'ノ',
	}, {
		'english': 'ha',
		'gif': 'katakana-ハ.gif',
		'png': 'katakana-ハ.png',
		'japanese': 'ハ',
	}, {
		'english': 'hi',
		'gif': 'katakana-ヒ.gif',
		'png': 'katakana-ヒ.png',
		'japanese': 'ヒ',
	}, {
		'english': 'fu',
		'gif': 'katakana-フ.gif',
		'png': 'katakana-フ.png',
		'japanese': 'フ',
	}, {
		'english': 'he',
		'gif': 'katakana-ヘ.gif',
		'png': 'katakana-ヘ.png',
		'japanese': 'ヘ',
	}, {
		'english': 'ho',
		'gif': 'katakana-ホ.gif',
		'png': 'katakana-ホ.png',
		'japanese': 'ホ',
	}, {
		'english': 'ma',
		'gif': 'katakana-マ.gif',
		'png': 'katakana-マ.png',
		'japanese': 'マ',
	}, {
		'english': 'mi',
		'gif': 'katakana-ミ.gif',
		'png': 'katakana-ミ.png',
		'japanese': 'ミ',
	}, {
		'english': 'mu',
		'gif': 'katakana-ム.gif',
		'png': 'katakana-ム.png',
		'japanese': 'ム',
	}, {
		'english': 'me',
		'gif': 'katakana-メ.gif',
		'png': 'katakana-メ.png',
		'japanese': 'メ',
	}, {
		'english': 'mo',
		'gif': 'katakana-モ.gif',
		'png': 'katakana-モ.png',
		'japanese': 'モ',
	}, {
		'english': 'ya',
		'gif': 'katakana-ヤ.gif',
		'png': 'katakana-ヤ.png',
		'japanese': 'ヤ',
	}, {
		'english': 'yu',
		'gif': 'katakana-ユ.gif',
		'png': 'katakana-ユ.png',
		'japanese': 'ユ',
	}, {
		'english': 'yo',
		'gif': 'katakana-ヨ.gif',
		'png': 'katakana-ヨ.png',
		'japanese': 'ヨ',
	}, {
		'english': 'ra',
		'gif': 'katakana-ラ.gif',
		'png': 'katakana-ラ.png',
		'japanese': 'ラ',
	}, {
		'english': 'ri',
		'gif': 'katakana-リ.gif',
		'png': 'katakana-リ.png',
		'japanese': 'リ',
	}, {
		'english': 'ru',
		'gif': 'katakana-ル.gif',
		'png': 'katakana-ル.png',
		'japanese': 'ル',
	}, {
		'english': 're',
		'gif': 'katakana-レ.gif',
		'png': 'katakana-レ.png',
		'japanese': 'レ',
	}, {
		'english': 'ro',
		'gif': 'katakana-ロ.gif',
		'png': 'katakana-ロ.png',
		'japanese': 'ロ',
	}, {
		'english': 'wa',
		'gif': 'katakana-ワ.gif',
		'png': 'katakana-ワ.png',
		'japanese': 'ワ',
	}, {
		'english': 'wo',
		'gif': 'katakana-ヲ.gif',
		'png': 'katakana-ヲ.png',
		'japanese': 'ヲ',
	}, {
		'english': 'n',
		'gif': 'katakana-ン.gif',
		'png': 'katakana-ン.png',
		'japanese': 'ン',
	}];

	return katakana;
}

export function fn_japanese() {

	const items = [{
		name: 'Hiragana',
		key: 'hiragana',
		characters: fn_hiragana(),
	}, {
		name: 'Katakana',
		key: 'katakana',
		characters: fn_katakana(),
	}]

	return items;
}
